name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Remove .git from clone
        run: make ignores

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: go-gitignore-it
